### ISSUE TITLE
Error on using KeyboardName in config

### ISSUE THREAD

**Issue by jromest** [DavRack/skr#19]
Following this [new method to define keyboards](https://github.com/DavRack/skr/pull/8), I got this error when using `KeyboardName` in the config.
```
Initializing skr
Traceback (most recent call last):
  File "/usr/bin/skr", line 126, in <module>
    keyboardPath = keyboardPathFromConfig(configFile)
  File "/usr/bin/skr", line 23, in keyboardPathFromConfig
    path = path.split("->")[1].strip()
IndexError: list index out of range
```

Here's my config file:
```
KeyboardName -> Keychron K6 Keyboard

Esc -> Grave
CapsLock -> Esc
```

**Comment by test482** [comment]
same issue here.
my laptop is ThinkPad T14 Gen 1, runinng Arch Linux.

"AT Translated Set 2 keyboard" is my laptop keyboard, (part of) `cat /proc/bus/input/devices` shows:
```
I: Bus=0011 Vendor=0001 Product=0001 Version=ab83
N: Name="AT Translated Set 2 keyboard"
P: Phys=isa0060/serio0/input0
S: Sysfs=/devices/platform/i8042/serio0/input/input4
U: Uniq=
H: Handlers=sysrq kbd leds event4 
B: PROP=0
B: EV=120013
B: KEY=402000000 3803078f800d001 feffffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=7
```

here my skr conf:
```
#KeyboardName -> AT Translated Set 2 keyboard
KeyboardPath -> /dev/input/event4

CapsLock -> Esc
```

skr work with KeyboardPath but not work with KeyboardName, the output log when using `KeyboardName -> AT Translated Set 2 keyboard` is same like @jromest says.
